// Date: 2/8/2015 7:45:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.straysify.moreitems.block;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Lamp extends ModelBase
{
  //fields
    ModelRenderer Shape6;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
  
  public Lamp()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape6 = new ModelRenderer(this, 35, 0);
      Shape6.addBox(0F, 0F, 0F, 2, 9, 2);
      Shape6.setRotationPoint(-1F, 14F, -1F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 8, 1, 8);
      Shape1.setRotationPoint(-4F, 23F, -4F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 1, 12);
      Shape2.addBox(0F, 0F, 0F, 1, 9, 6);
      Shape2.setRotationPoint(2F, 14F, -3F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 16, 14);
      Shape3.addBox(0F, 0F, 0F, 5, 9, 1);
      Shape3.setRotationPoint(-3F, 14F, 2F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 46, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 9, 5);
      Shape4.setRotationPoint(-3F, 14F, -3F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 59, 0);
      Shape5.addBox(0F, 0F, 0F, 4, 9, 1);
      Shape5.setRotationPoint(-2F, 14F, -3F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 76, 0);
      Shape7.addBox(0F, 0F, 0F, 8, 1, 8);
      Shape7.setRotationPoint(-4F, 13F, -4F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 30, 19);
      Shape8.addBox(0F, 0F, 0F, 6, 1, 6);
      Shape8.setRotationPoint(-3F, 12F, -3F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 57, 16);
      Shape9.addBox(0F, 0F, 0F, 4, 1, 4);
      Shape9.setRotationPoint(-2F, 11F, -2F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 34, 13);
      Shape10.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape10.setRotationPoint(-1F, 10F, -1F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape6.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
  }
  
  public void renderModel(float f) {
	    Shape6.render(f);
	    Shape1.render(f);
	    Shape2.render(f);
	    Shape3.render(f);
	    Shape4.render(f);
	    Shape5.render(f);
	    Shape7.render(f);
	    Shape8.render(f);
	    Shape9.render(f);
	    Shape10.render(f);
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
